import asyncHandler from 'express-async-handler';
import Category from '../models/Category.js';

// @desc    Get all categories
// @route   GET /api/categories
// @access  Public
export const getCategories = asyncHandler(async (req, res) => {
    const categories = await Category.find({ isActive: true }).sort('sequence');
    res.json({ success: true, data: categories });
});

// @desc    Get single category
// @route   GET /api/categories/:id
// @access  Public
export const getCategoryById = asyncHandler(async (req, res) => {
    const category = await Category.findById(req.params.id);

    if (category) {
        res.json({ success: true, data: category });
    } else {
        res.status(404);
        throw new Error('Category not found');
    }
});

// @desc    Create a category
// @route   POST /api/categories
// @access  Private/Admin
export const createCategory = asyncHandler(async (req, res) => {
    const { name, icon, description, image, sequence } = req.body;

    const categoryExists = await Category.findOne({ name });

    if (categoryExists) {
        res.status(400);
        throw new Error('Category already exists');
    }

    const targetSequence = Number(sequence) || 0;

    // Handle Sequence Conflict (Defensive)
    const conflictingCategory = await Category.findOne({ sequence: targetSequence });
    if (conflictingCategory) {
        const lastCategory = await Category.findOne({}).sort('-sequence');
        const maxSequence = lastCategory ? lastCategory.sequence : 0;

        // Move conflicting category to end
        conflictingCategory.sequence = maxSequence + 1;
        await conflictingCategory.save();
    }

    // Slug is generated by pre-save hook in model
    const category = await Category.create({
        name,
        icon,
        description,
        image,
        sequence: targetSequence
    });

    if (category) {
        res.status(201).json({
            success: true,
            data: category,
        });
    } else {
        res.status(400);
        throw new Error('Invalid category data');
    }
});

// @desc    Update a category
// @route   PUT /api/categories/:id
// @access  Private/Admin
export const updateCategory = asyncHandler(async (req, res) => {
    const category = await Category.findById(req.params.id);

    if (category) {
        const originalSequence = category.sequence;
        const newSequence = req.body.sequence !== undefined ? Number(req.body.sequence) : undefined;

        // Check/Handle Sequence Conflict
        if (newSequence !== undefined && newSequence !== originalSequence) {
            const conflictingCategory = await Category.findOne({ sequence: newSequence });

            if (conflictingCategory) {
                // Find current max sequence
                const lastCategory = await Category.findOne({}).sort('-sequence');
                const maxSequence = lastCategory ? lastCategory.sequence : 0;

                // Move conflicting category to end
                conflictingCategory.sequence = maxSequence + 1;
                await conflictingCategory.save();
            }
        }

        // Standard Update (No Sequence Change or No Collision)
        category.name = req.body.name || category.name;
        category.icon = req.body.icon || category.icon;
        category.description = req.body.description || category.description;
        category.image = req.body.image || category.image;
        category.sequence = req.body.sequence !== undefined ? req.body.sequence : category.sequence;
        category.isActive = req.body.isActive !== undefined ? req.body.isActive : category.isActive;

        if (req.body.name) {
            category.slug = req.body.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
        }

        const updatedCategory = await category.save();
        res.json({
            success: true,
            data: updatedCategory,
        });
    } else {
        res.status(404);
        throw new Error('Category not found');
    }
});

// @desc    Delete a category
// @route   DELETE /api/categories/:id
// @access  Private/Admin
export const deleteCategory = asyncHandler(async (req, res) => {
    const category = await Category.findById(req.params.id);

    if (category) {
        await category.deleteOne();
        res.json({ success: true, message: 'Category removed' });
    } else {
        res.status(404);
        throw new Error('Category not found');
    }
});
